ANDROID_ARMV8_BUILD_DIR	:= $(BUILD_DIR)/ARMv8
ANDROID_ARMV8_LIB_DIR	:= $(ANDROID_APK_LIB_DIR)/arm64-v8a
ANDROID_ARMV8_TARGET	:= $(ANDROID_ARMV8_LIB_DIR)/lib$(CONFIG_PROJECT_NAME).so
ANDROID_ARMV8_OBJECTS	:= $(patsubst $(BUILD_DIR)/%.o, $(ANDROID_ARMV8_BUILD_DIR)/%.o, $(OBJECTS))
ANDROID_ARMV8_CC		:= aarch64-linux-android$(CONFIG_ANDROID_SDK_VERSION)-clang

ifdef CONFIG_RENDERER_VULKAN
$(ANDROID_ARMV8_BUILD_DIR)/shader.o: $(VULKAN_SPV)
endif

$(ANDROID_ARMV8_TARGET): $(ANDROID_ARMV8_OBJECTS)
	@ mkdir -p $(@D)
	@ $(ANDROID_ARMV8_CC) $(ANDROID_ARMV8_OBJECTS) -o $@ $(LDFLAGS)
	$(info Linking $@)

$(ANDROID_ARMV8_BUILD_DIR)/%.o: %.c
	@ mkdir -p $(@D)
	@ $(ANDROID_ARMV8_CC) $(CFLAGS) $< -o $@
	$(info Compilling $< (ARMv8))
