PLATFORM_DIR	:= $(PLATFORMS_DIR)/android
TARGET			:= $(BUILD_DIR)/$(CONFIG_PROJECT_NAME).apk
VPATH			:= $(VPATH) $(PLATFORM_DIR)/source

## Apk Config ##

CONFIG_PROJECT_VERSION_FULL_STR	:= $(CONFIG_PROJECT_VERSION_MAJOR)
CONFIG_PROJECT_VERSION_FULL_STR	:= $(CONFIG_PROJECT_VERSION_FULL_STR).$(CONFIG_PROJECT_VERSION_MINOR)
CONFIG_PROJECT_VERSION_FULL_STR	:= $(CONFIG_PROJECT_VERSION_FULL_STR).$(CONFIG_PROJECT_VERSION_PATCH)

CONFIG_PROJECT_VERSION_FULL		:= $(CONFIG_PROJECT_VERSION_MAJOR)
CONFIG_PROJECT_VERSION_FULL		:= $(shell expr 100 \* $(CONFIG_PROJECT_VERSION_FULL) + $(CONFIG_PROJECT_VERSION_MINOR))
CONFIG_PROJECT_VERSION_FULL		:= $(shell expr 100 \* $(CONFIG_PROJECT_VERSION_FULL) + $(CONFIG_PROJECT_VERSION_PATCH))
CONFIG_PROJECT_VERSION_FULL		:= $(shell expr 100 \* $(CONFIG_PROJECT_VERSION_FULL) + $(CONFIG_ENGINE_VERSION_MAJOR))
CONFIG_PROJECT_VERSION_FULL		:= $(shell expr 100 \* $(CONFIG_PROJECT_VERSION_FULL) + $(CONFIG_ENGINE_VERSION_MINOR))
CONFIG_PROJECT_VERSION_FULL		:= $(shell expr 100 \* $(CONFIG_PROJECT_VERSION_FULL) + $(CONFIG_ENGINE_VERSION_PATCH))

CONFIG_APK_KEY_CN				:= $(patsubst "%",%, $(CONFIG_APK_KEY_CN))
CONFIG_APK_KEY_OU				:= $(patsubst "%",%, $(CONFIG_APK_KEY_OU))
CONFIG_APK_KEY_O				:= $(patsubst "%",%, $(CONFIG_APK_KEY_O))
CONFIG_APK_KEY_L				:= $(patsubst "%",%, $(CONFIG_APK_KEY_L))
CONFIG_APK_KEY_ST				:= $(patsubst "%",%, $(CONFIG_APK_KEY_ST))
CONFIG_APK_KEY_C				:= $(patsubst "%",%, $(CONFIG_APK_KEY_C))
CONFIG_APK_KEY_PASSWORD			:= $(patsubst "%",%, $(CONFIG_APK_KEY_PASSWORD))
CONFIG_ANDROID_SDK_PATH			:= $(patsubst "%",%, $(CONFIG_ANDROID_SDK_PATH))
CONFIG_ANDROID_NDK_PATH			:= $(patsubst "%",%, $(CONFIG_ANDROID_NDK_PATH))
CONFIG_ANDROID_BUILD_TOOLS_PATH	:= $(patsubst "%",%, $(CONFIG_ANDROID_BUILD_TOOLS_PATH))

ANDROID_APK_KEY_INFO		:= CN=$(CONFIG_APK_KEY_CN)
ANDROID_APK_KEY_INFO		:= $(ANDROID_APK_KEY_INFO),OU=$(CONFIG_APK_KEY_OU)
ANDROID_APK_KEY_INFO		:= $(ANDROID_APK_KEY_INFO),O=$(CONFIG_APK_KEY_O)
ANDROID_APK_KEY_INFO		:= $(ANDROID_APK_KEY_INFO),L=$(CONFIG_APK_KEY_L)
ANDROID_APK_KEY_INFO		:= $(ANDROID_APK_KEY_INFO),ST=$(CONFIG_APK_KEY_ST)
ANDROID_APK_KEY_INFO		:= $(ANDROID_APK_KEY_INFO),C=$(CONFIG_APK_KEY_C)
ANDROID_SDK_INFO_PATH		:= $(CONFIG_ANDROID_SDK_PATH)/build.prop
ANDROID_NDK_BIN_PATH		:= $(CONFIG_ANDROID_NDK_PATH)/toolchains/llvm/prebuilt
CONFIG_ANDROID_SDK_VERSION	:= $(call get-prop, $(ANDROID_SDK_INFO_PATH), ro.build.version.sdk)

ifdef OS_LINUX
ANDROID_NDK_BIN_PATH := $(ANDROID_NDK_BIN_PATH)/linux-x86_64/bin
endif

ifeq ($(CONFIG_ANDROID_TARGET_PLATFORM), 0)
CONFIG_ANDROID_TARGET_PLATFORM := $(CONFIG_ANDROID_SDK_VERSION)
endif

export CONFIG_PROJECT_NAME				:= $(CONFIG_PROJECT_NAME)
export CONFIG_PROJECT_VERSION_FULL_STR	:= $(CONFIG_PROJECT_VERSION_FULL_STR)
export CONFIG_PROJECT_VERSION_FULL		:= $(CONFIG_PROJECT_VERSION_FULL)
export CONFIG_ANDROID_SDK_VERSION		:= $(CONFIG_ANDROID_SDK_VERSION)
export CONFIG_ANDROID_TARGET_PLATFORM	:= $(CONFIG_ANDROID_TARGET_PLATFORM)
export CONFIG_PROJECT_PACKAGE			:= com.$(CONFIG_ENGINE_NAME).$(CONFIG_PROJECT_NAME)

## Compiler Flags ##

CFLAGS	:= $(CFLAGS) -flto -fpic -I $(PLATFORM_DIR)/api
LDFLAGS	:= $(LDFLAGS) -flto -shared -llog

ifdef CONFIG_RENDERER_VULKAN
LDFLAGS	:= $(LDFLAGS) -lvulkan
endif

ANDROID_SDK_JAR				:= $(CONFIG_ANDROID_SDK_PATH)/android.jar
ANDROID_APK_KEY_PATH		:= $(BUILD_DIR)/$(CONFIG_PROJECT_NAME).jks
ANDROID_APK_UNSIGNED_PATH	:= $(BUILD_DIR)/$(CONFIG_PROJECT_NAME).uapk
ANDROID_JAVA_BUILD_DIR		:= $(BUILD_DIR)/java
ANDROID_JAVA_CLASS_DIR		:= $(ANDROID_JAVA_BUILD_DIR)/$(subst .,/,$(CONFIG_PROJECT_PACKAGE))
ANDROID_APK_BUILD_DIR		:= $(BUILD_DIR)/apk
ANDROID_APK_LIB_DIR			:= $(ANDROID_APK_BUILD_DIR)/lib
ANDROID_APK_DEX_PATH		:= $(ANDROID_APK_BUILD_DIR)/classes.dex

ANDROID_JAVA_FLAGS		:= -Xlint:-options
ANDROID_JAVA_FLAGS		:= $(ANDROID_JAVA_FLAGS) --release 7
ANDROID_APK_KEY_FLAGS	:= -genkey -keyalg RSA -keysize 2048
ANDROID_APK_KEY_FLAGS	:= $(ANDROID_APK_KEY_FLAGS) -dname $(ANDROID_APK_KEY_INFO)
ANDROID_APK_KEY_FLAGS	:= $(ANDROID_APK_KEY_FLAGS) -keypass $(CONFIG_APK_KEY_PASSWORD)
ANDROID_APK_KEY_FLAGS	:= $(ANDROID_APK_KEY_FLAGS) -storepass $(CONFIG_APK_KEY_PASSWORD)
ANDROID_APK_SIGN_FLAGS	:= --ks-pass pass:$(CONFIG_APK_KEY_PASSWORD)

## Build Tools ##

PATH					:= $(PATH):$(CONFIG_ANDROID_BUILD_TOOLS_PATH)
PATH					:= $(PATH):$(ANDROID_NDK_BIN_PATH)
ANDROID_APK_INSTALLED	 = $(shell adb shell pm list packages $(CONFIG_PROJECT_PACKAGE))

## Sources ##

ANDROID_JAVA_SOURCES	:= MainActivity.java
ANDROID_JAVA_OBJECTS	:= $(patsubst %.java, $(ANDROID_JAVA_CLASS_DIR)/%.class, $(ANDROID_JAVA_SOURCES))
.PRECIOUS				:  $(patsubst %.java, $(BUILD_DIR)/%.java, $(ANDROID_JAVA_SOURCES))

SOURCES := window.c
SOURCES := $(SOURCES) android_main.c
SOURCES := $(SOURCES) android_logger.c
SOURCES := $(SOURCES) android_options.c
OBJECTS := $(OBJECTS) $(patsubst %.c, $(BUILD_DIR)/%.o, $(SOURCES))

## Targets ##

ifdef CONFIG_ARCH_ARMV7
include $(PLATFORM_DIR)/arch-armv7.mk
endif

ifdef CONFIG_ARCH_ARMV8
include $(PLATFORM_DIR)/arch-armv8.mk
endif

ifdef CONFIG_ARCH_X86
include $(PLATFORM_DIR)/arch-x86.mk
endif

ifdef CONFIG_ARCH_X64
include $(PLATFORM_DIR)/arch-x64.mk
endif

all:								$(TARGET)
$(BUILD_DIR)/AndroidManifest.xml:	$(ANDROID_SDK_INFO_PATH)
$(ANDROID_APK_UNSIGNED_PATH):		$(ANDROID_APK_DEX_PATH)
$(ANDROID_APK_UNSIGNED_PATH):		$(ANDROID_ARMV8_TARGET)

adb-install: $(TARGET) adb-uninstall
	@ adb install -r $<
	$(info Installing $<)

adb-run: adb-install
	@ adb shell am start -n $(CONFIG_PROJECT_PACKAGE)/.MainActivity
	$(info Running $(CONFIG_PROJECT_PACKAGE).MainActivity)

adb-uninstall:
	@ $(if $(ANDROID_APK_INSTALLED), \
		adb uninstall $(CONFIG_PROJECT_PACKAGE) \
		$(info Uninstalling $(CONFIG_PROJECT_PACKAGE)))

$(TARGET): $(ANDROID_APK_UNSIGNED_PATH) $(ANDROID_APK_KEY_PATH)
	@ apksigner sign $(ANDROID_APK_SIGN_FLAGS) --ks $(ANDROID_APK_KEY_PATH) --out $@ --in $<
	$(info Signing $@)

$(ANDROID_APK_KEY_PATH): $(KCONFIG_CONFIG)
	@ rm -f $@
	@ mkdir -p $(@D)
	@ keytool $(ANDROID_APK_KEY_FLAGS) -keystore $@
	$(info Generating $@)

$(ANDROID_APK_UNSIGNED_PATH): $(BUILD_DIR)/AndroidManifest.xml $(ANDROID_SDK_JAR)
	@ aapt package -fM $< -F $@ -I $(ANDROID_SDK_JAR) $(ANDROID_APK_BUILD_DIR)
	$(info Building $@)

$(BUILD_DIR)/%.xml: $(PLATFORM_DIR)/%.xml $(KCONFIG_CONFIG)
	@ mkdir -p $(@D)
	@ envsubst > $@ < $<
	$(info Generating $@)

$(ANDROID_APK_DEX_PATH): $(ANDROID_JAVA_OBJECTS)
	@ mkdir -p $(@D)
	@ dx --dex --output $@ $(ANDROID_JAVA_BUILD_DIR)
	$(info Linking $@)

$(ANDROID_JAVA_CLASS_DIR)/%.class: $(BUILD_DIR)/%.java $(ANDROID_SDK_JAR)
	@ mkdir -p $(@D)
	@ javac $(ANDROID_JAVA_FLAGS) -cp $(ANDROID_SDK_JAR) -d $(ANDROID_JAVA_BUILD_DIR) $<
	$(info Compilling $<)

$(BUILD_DIR)/%.java: %.java $(KCONFIG_CONFIG)
	@ mkdir -p $(@D)
	@ envsubst > $@ < $<
	$(info Generating $@)
